SELECT DISTINCT s.WorkOrder
FROM SCM_PROJECT_COMPONENT p WITH(NOLOCK)
INNER JOIN SCM_B2B_SERIAL_NUMBER s WITH(NOLOCK)
ON (p.COMPONENT_SERIAL_NUMBER = s.SerialNumber)
WHERE p.PROJECT_ID = @pattern_name